create extension if not exists pgcrypto;

create table if not exists public.certificates (
  cert_id text primary key,
  issuer text,
  metadata_cid text,
  file_cid text,
  file_hash text,
  version int,
  replaces_cert_id text null,
  revoked boolean not null default false,
  issue_tx text,
  revoke_tx text null,
  block_number bigint,
  revoke_block_number bigint null,
  issued_at bigint,
  revoked_at bigint null,
  updated_at timestamptz not null default now()
);

create index if not exists certificates_issuer_idx on public.certificates (issuer);
create index if not exists certificates_block_number_idx on public.certificates (block_number desc);
create index if not exists certificates_replaces_idx on public.certificates (replaces_cert_id);

create table if not exists public.indexer_state (
  id text primary key,
  last_block bigint not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.issuer_status (
  issuer text primary key,
  is_authorized boolean not null,
  last_tx_hash text,
  last_block_number bigint,
  last_changed_at bigint,
  changed_by text null,
  updated_at timestamptz not null default now()
);

create index if not exists issuer_status_authorized_idx on public.issuer_status (is_authorized);
create index if not exists issuer_status_last_block_idx on public.issuer_status (last_block_number desc);

create table if not exists public.issuer_events (
  tx_hash text not null,
  log_index int not null,
  block_number bigint not null,
  issuer text not null,
  allowed boolean not null,
  changed_by text null,
  changed_at bigint null,
  created_at timestamptz not null default now(),
  primary key (tx_hash, log_index)
);

create index if not exists issuer_events_issuer_idx on public.issuer_events (issuer);
create index if not exists issuer_events_block_idx on public.issuer_events (block_number desc);

create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  email text unique not null,
  password_hash text not null,
  role text not null check (role in ('MOE_ADMIN','INSTITUTION_ADMIN','INDIVIDUAL')),
  email_verified boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.institutions (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  status text not null check (status in ('PENDING','ACTIVE','SUSPENDED')),
  admin_email text not null,
  issuer_wallet text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.institution_users (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  institution_id uuid not null references public.institutions(id) on delete cascade,
  is_primary_admin boolean not null default false,
  created_at timestamptz not null default now(),
  unique (user_id, institution_id)
);

create table if not exists public.invitations (
  id uuid primary key default gen_random_uuid(),
  institution_id uuid not null references public.institutions(id) on delete cascade,
  email text not null,
  token_hash text not null,
  expires_at timestamptz not null,
  used_at timestamptz null,
  created_at timestamptz not null default now()
);

create table if not exists public.wallet_bindings (
  id uuid primary key default gen_random_uuid(),
  institution_id uuid not null references public.institutions(id) on delete cascade,
  wallet_address text not null,
  verified boolean not null default false,
  verified_at timestamptz null,
  created_at timestamptz not null default now(),
  unique (institution_id, wallet_address)
);

create table if not exists public.refresh_tokens (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  token_hash text not null,
  expires_at timestamptz not null,
  revoked_at timestamptz null,
  created_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_user_id uuid null references public.users(id) on delete set null,
  actor_wallet text null,
  action text not null,
  entity_type text not null,
  entity_id text null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists users_email_idx on public.users (email);
create index if not exists institutions_status_idx on public.institutions (status);
create index if not exists invitations_token_hash_idx on public.invitations (token_hash);
create index if not exists wallet_bindings_inst_idx on public.wallet_bindings (institution_id);
create index if not exists refresh_tokens_user_idx on public.refresh_tokens (user_id);
create index if not exists refresh_tokens_hash_idx on public.refresh_tokens (token_hash);
create index if not exists audit_logs_actor_idx on public.audit_logs (actor_user_id);
create index if not exists audit_logs_action_idx on public.audit_logs (action);
